spring.application.name=chatApp

server.port=8085

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/chat_application
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
server.debug.port=5005

# Server Configuration

# JWT Configuration
jwt.secretKey=adgasd8d798h7097knfd097097hdh77jfd709djflknbhdfb5453hadfxz

# Email Configurations
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sharmasachinwins@gmail.com
spring.mail.password=sqxh mgha wtsr gfmm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#OAuthConfigurations
deploy.env = development
